## Group Authenticate APP

### Authenticate With Callback [/_callback.json]

Will return _null_ response with _204_ status code,
token and ID will be sent to application `auth_callback_uri`
with a _POST_ callback request

The callback body with the follow the model below:

```json
{
  "my_id": "100000000000000000000012",
  "access_token": "eyJhbGciOi.eyYzdWIi.ZEONFh7HgQ",
  "expires": "2017-12-02T08:02:17-05:00"
}
```

Generated token is valid for one day, as defined by *expires* ISO 8601 date and time,
then you will need to generate another token

#### Request Access Token [POST]

+ Request (application/json)

    + Headers

            X-Store-ID: 100

    + Attributes (object)
        + _id: 100000000000000000000012 (string, required)
            Authentication object ID

    + Body

            {
              "_id": "100000000000000000000012"
            }

+ Response 204 (application/json)
