FORMAT: 1A
HOST: https://sandbox.e-com.plus/v1/

# E-Com Plus Store API

[E-Com Plus](https://www.e-com.plus)
is a robust and flexible cloud commerce software,
totally based on REST APIs, providing a large library of methods and specifications
to deploy any digital commerce operation easly

**Store API** is the "hearth" of our software, a REST interface to the
[MongoDB](https://www.mongodb.com/) stores database,
given full access to all store data

Be creative, but be careful too, _with great power comes great responsibility_,
_may the force be with you_!
