### Application Data [/applications/{_id}/data.json]

`.applications.data`

Use the **data** subresource to read and update an specific app data in
a merchant's store.

*/applications/[_id]/data.json*

> Authentication<br>_GET_, _PUT_: **required**

+ Attributes (object)
    + `data` (object, required) - App data, limitations: https://docs.mongodb.com/manual/reference/limits/#bson-documents

#### JSON Schema [GET /applications/schema/data.json]

+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
                "$schema": "http://json-schema.org/draft-06/schema#",
                "title": "Application data",
                "type": "object",
                "required": [
                    "data"
                ],
                "additionalProperties": false,
                "properties": {
                    "data": {
                        "type": "object",
                        "description": "App data, limitations: https://docs.mongodb.com/manual/reference/limits/#bson-documents"
                    }
                }
            }

#### Read Application Data [GET]

+ Parameters
    + _id: 42aa00000000000000000111 (string, required) - The application ID

+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 10000000000000000000000f

+ Response 200 (application/json)

    + Body

            {
              "sample": 123,
              "eg": [ 1, 2, 3 ]
            }
