### Application Data [/applications/{_id}/data.json]

*/applications/[_id]/data.json*

> Authentication<br>_GET_, _PUT_: **required**

Use the **data** subresource to read and update an specific app data in
a merchant's store.

### Application Data Object [/applications/schema/data.json]

+ Attributes (object)
    + `data` (object, required) - App data, limitations: https://docs.mongodb.com/manual/reference/limits/#bson-documents

#### JSON Schema [GET]

+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
                "$schema": "http://json-schema.org/draft-06/schema#",
                "title": "Application data",
                "type": "object",
                "required": [
                    "data"
                ],
                "additionalProperties": false,
                "properties": {
                    "data": {
                        "type": "object",
                        "description": "App data, limitations: https://docs.mongodb.com/manual/reference/limits/#bson-documents"
                    }
                }
            }
