### Application Hidden Data [/applications/{_id}/hidden_data.json]

`.applications.hidden_data`

Use the **hidden_data** subresource to read and update an
specific app private data, such as tokens and secret keys.

*/applications/[_id]/hidden_data.json*

> Authentication<br>_GET_, _PUT_: **required**

+ Attributes (object)
    + `hidden_data` (object, required) - App private data, limits: https://docs.mongodb.com/manual/reference/limits/#bson-documents

#### JSON Schema [GET /applications/schema/hidden_data.json]

+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

              {
                  "$schema": "http://json-schema.org/draft-06/schema#",
                  "title": "Application private data, available only with authentication",
                  "type": "object",
                  "required": [
                      "hidden_data"
                  ],
                  "additionalProperties": false,
                  "properties": {
                      "hidden_data": {
                          "type": "object",
                          "description": "App data, limitations: https://docs.mongodb.com/manual/reference/limits/#bson-documents"
                      }
                  }
              }
