+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 1000,
                "offset": 0,
                "sort": [],
                "fields": [
                  "_id",
                  "available",
                  "completed",
                  "permalink",
                  "status",
                  "customers",
                  "items.product_id",
                  "items.sku",
                  "items.name",
                  "items.quantity",
                  "subtotal",
                  "discount",
                  "created_at",
                  "updated_at"
                ],
                "query": {}
              },
              "result": [
                {
                  "_id": "5c6b159ec626be23430d4e87",
                  "available": true,
                  "completed": false,
                  "items": [
                    {
                      "sku": "IPZ7060-613-1",
                      "product_id": "5bbbb3ea2707d825d174c0c5",
                      "quantity": 168,
                      "name": "T-Shirt / S"
                    },
                    {
                      "sku": "IPZ7060-507-2",
                      "product_id": "5bbbb3ea2707d825d174c0c5",
                      "quantity": 168,
                      "name": "T-Shirt / M"
                    }
                  ],
                  "subtotal": 4200,
                  "status": "Production",
                  "updated_at": "2019-02-18T20:33:04.856Z",
                  "created_at": "2019-02-18T20:33:04.856Z"
                },
                {
                  "_id": "5c70531ac626be23430d5047",
                  "items": [
                    {
                      "product_id": "5c703e79c626be23430d5038",
                      "quantity": 1
                    }
                  ],
                  "subtotal": 16005.51,
                  "available": true,
                  "completed": false,
                  "created_at": "2019-02-22T19:52:58.033Z"
                },
                {
                  "_id": "5c9902976d0a665f892a250a",
                  "items": [
                    {
                      "product_id": "5c703e79c626be23430d5038",
                      "quantity": 1
                    }
                  ],
                  "subtotal": 16005.51,
                  "available": true,
                  "completed": false,
                  "created_at": "2019-03-25T16:32:23.703Z"
                },
                {
                  "_id": "5c9904476d0a665f892a250f",
                  "items": [
                    {
                      "product_id": "5c768fcfc626be23430d5090",
                      "quantity": 1
                    }
                  ],
                  "subtotal": 820.14,
                  "available": true,
                  "completed": false,
                  "created_at": "2019-03-25T16:39:35.044Z"
                }
              ]
            }
