+ Request (application/json)

    + Headers

            X-Store-ID: 100
            X-Access-Token: eyJhbGciOi.eyJzdWIi.AFONFh7HgQ
            X-My-ID: 5a6757722b66f68dbed44526

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 1000,
                "offset": 0,
                "sort": [],
                "fields": [
                  "_id",
                  "state",
                  "enabled",
                  "login",
                  "status",
                  "main_email",
                  "accepts_marketing",
                  "display_name",
                  "orders_count",
                  "orders_total_value",
                  "created_at",
                  "updated_at"
                ],
                "query": {}
              },
              "result": [
                {
                  "_id": "3c1000000000000000000001",
                  "state": "invited",
                  "enabled": true,
                  "login": true,
                  "main_email": "123@mail.com",
                  "display_name": "Fulano",
                  "accepts_marketing": true,
                  "created_at": "2019-01-21T13:53:57.065Z"
                },
                {
                  "_id": "5bf563757f2ea911aecb8f6b",
                  "state": "registered",
                  "enabled": true,
                  "login": true,
                  "status": "ok",
                  "main_email": "matt@s2gmail.com",
                  "display_name": "Matt",
                  "accepts_marketing": false,
                  "created_at": "2018-11-21T13:53:57.065Z"
                },
                {
                  "_id": "3c1000000000000000000004",
                  "state": "registered",
                  "enabled": false,
                  "login": false,
                  "status": "untrusted",
                  "main_email": "456@mail.com",
                  "display_name": "Richard",
                  "created_at": "2019-01-30T14:05:10.010Z",
                  "updated_at": "2019-04-01T19:03:47.719Z",
                  "accepts_marketing": true,
                  "orders_count": 10
                },
                {
                  "_id": "3c1000000000000000000005",
                  "state": "registered",
                  "enabled": true,
                  "login": true,
                  "status": "star",
                  "main_email": "janerue@mail.ex",
                  "display_name": "Jane Rue",
                  "created_at": "2019-01-30T14:05:10.010Z",
                  "updated_at": "2019-04-01T19:03:47.719Z",
                  "accepts_marketing": true,
                  "orders_count": 2,
                  "orders_total_value": 1535
                },
                {
                  "_id": "3c1000000000000000000006",
                  "state": "registered",
                  "enabled": true,
                  "login": false,
                  "status": "buy_only",
                  "main_email": "abc@mail.com",
                  "display_name": "Name",
                  "created_at": "2019-04-01T19:08:56.371Z",
                  "updated_at": "2019-04-01T19:11:03.398Z",
                  "accepts_marketing": false,
                  "orders_count": 1,
                  "orders_total_value": 767.5
                }
              ]
            }
