+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 1000,
                "offset": 0,
                "sort": [],
                "fields": [
                  "_id",
                  "title",
                  "grid_id",
                  "options.option_id",
                  "options.text",
                  "options.colors",
                  "created_at",
                  "updated_at"
                ],
                "query": {}
              },
              "result": [
                {
                  "_id": "5c81415cc626be23430d50be",
                  "title": "Connector",
                  "grid_id": "conector",
                  "options": [
                    {
                      "text": "P2",
                      "option_id": "p2"
                    },
                    {
                      "text": "USB",
                      "option_id": "usb"
                    }
                  ],
                  "updated_at": "2019-03-07T19:56:39.024Z",
                  "created_at": "2019-03-07T19:56:39.024Z"
                },
                {
                  "_id": "5c8141b6c626be23430d50c3",
                  "title": "DPI",
                  "grid_id": "dpi",
                  "options": [
                    {
                      "text": "16400",
                      "option_id": "16400"
                    },
                    {
                      "text": "4000",
                      "option_id": "4000"
                    },
                    {
                      "text": "6000",
                      "option_id": "6000"
                    }
                  ],
                  "updated_at": "2019-03-07T19:47:34.185Z",
                  "created_at": "2019-03-07T19:47:34.185Z"
                },
                {
                  "_id": "5c8151d2c626be23430d50cc",
                  "title": "Colors",
                  "grid_id": "colors",
                  "options": [
                    {
                      "text": "White",
                      "option_id": "white",
                      "colors": [
                        "#ffffff"
                      ]
                    },
                    {
                      "text": "Yellow",
                      "option_id": "yellow",
                      "colors": [
                        "#ffcc00"
                      ]
                    },
                    {
                      "text": "Purple",
                      "option_id": "purple",
                      "colors": [
                        "#c400ff"
                      ]
                    },
                    {
                      "text": "Green",
                      "option_id": "green",
                      "colors": [
                        "#09ff00"
                      ]
                    },
                    {
                      "text": "Wood",
                      "option_id": "wood",
                      "colors": [
                        "#852100"
                      ]
                    }
                  ],
                  "updated_at": "2019-03-07T20:21:10.081Z",
                  "created_at": "2019-03-07T20:21:10.081Z"
                }
              ]
            }
