+ Request (application/json)

    + Headers

            X-Store-ID: 100

+ Response 200 (application/json)

    + Body

            {
              "meta": {
                "limit": 1000,
                "offset": 0,
                "sort": [],
                "fields": [
                  "_id",
                  "name",
                  "slug",
                  "parent",
                  "icon",
                  "created_at",
                  "updated_at"
                ],
                "query": {}
              },
              "result": [
                {
                  "_id": "b10000000000000000001110",
                  "name": "Category 0",
                  "slug": "category-zero",
                  "icon": {
                    "url": "https://sample.shop.eg/assets/category.svg",
                    "size": "60x60"
                  },
                  "updated_at": "2019-02-22T13:36:06.547Z",
                  "created_at": "2019-02-22T13:36:06.547Z"
                },
                {
                  "_id": "b10000000000000000001111",
                  "name": "Category 1",
                  "slug": "category-one",
                  "parent": {
                    "_id": "b10000000000000000001110",
                    "name": "Category 0",
                    "slug": "category-zero"
                  },
                  "created_at": "2019-02-22T14:43:40.647Z"
                },
                {
                  "_id": "b10000000000000000001112",
                  "name": "Category 2",
                  "slug": "category-two",
                  "parent": {
                    "_id": "b10000000000000000001111",
                    "name": "Category 1",
                    "slug": "category-one"
                  },
                  "created_at": "2019-02-22T16:00:49.671Z"
                },
                {
                  "_id": "b10000000000000000001113",
                  "name": "Category 3",
                  "slug": "category-three",
                  "parent": {
                    "_id": "b10000000000000000001112",
                    "name": "Category 2",
                    "slug": "category-two"
                  },
                  "updated_at": "2019-02-22T13:36:06.547Z",
                  "created_at": "2019-02-22T13:36:06.547Z"
                },
                {
                  "_id": "b10000000000000000001114",
                  "name": "Category 4",
                  "slug": "category-four",
                  "parent": {
                    "_id": "b10000000000000000001113",
                    "name": "Category 3",
                    "slug": "category-three"
                  },
                  "created_at": "2019-02-22T16:00:49.671Z"
                },
                {
                  "_id": "b10000000000000000001115",
                  "name": "Category 5",
                  "slug": "category-five",
                  "created_at": "2019-02-22T14:41:59.607Z"
                },
                {
                  "_id": "b10000000000000000001116",
                  "name": "Category 6",
                  "slug": "category-six",
                  "parent": {
                    "_id": "b10000000000000000001115",
                    "name": "Category 5",
                    "slug": "category-five"
                  },
                  "created_at": "2019-02-22T14:41:01.323Z"
                },
                {
                  "_id": "f10000000000000000000001",
                  "name": "Polo Shirts",
                  "slug": "polo",
                  "parent": {
                    "_id": "b10000000000000000001110",
                    "name": "Category 0",
                    "slug": "category-zero"
                  },
                  "created_at": "2019-02-22T16:01:38.850Z"
                }
              ]
            }
